version: '3.7'
services:
  api:
    build: .
    ports:
      - 5000:5000
    networks:
      - url-shortener
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data/redis
    networks:
      - url-shortener

networks:
  url-shortener:
    driver: bridge

volumes:
  redis-data:
