version: '3.7'
services:
  url-shortener:
    build: .
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:5000
      - AUTH_SERVICE_URL=http://auth-service:5001/auth
    networks:
      - url-shortener
      - shared-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data/redis
    networks:
      - url-shortener

networks:
  url-shortener:
    driver: bridge
  shared-network:
    name: shared-network
    driver: external

volumes:
  redis-data:
