apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: ghcr.io/qimolin/url-shortener:latest
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: BASE_URL
            value: "http://localhost:5000"
          - name: AUTH_SERVICE_URL
            value: "http://auth-service:5001/auth"
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
